"""RESULTS.md from run directories and benchmark files - no number is typed by hand.

Per run: parallel mode, world size, device, steps, tokens seen, median tokens/s and MFU over the
logged steps that are not flagged ``timing_warmup``, peak memory, final validation loss and the
latest HellaSwag record. Every row names its run id; the manifest's git sha and peak source are
listed under the table. LayerNorm benchmark files (``bench/*.json``) become a second table.
"""

from __future__ import annotations

import json
import statistics
from pathlib import Path
from typing import Any


def read_log(run_dir: Path) -> list[dict[str, Any]]:
    path = run_dir / "log.jsonl"
    if not path.is_file():
        return []
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


def summarize_run(run_dir: Path) -> dict[str, Any] | None:
    manifest_path = run_dir / "manifest.json"
    if not manifest_path.is_file():
        return None
    manifest = json.loads(manifest_path.read_text())
    records = read_log(run_dir)
    steps = [r for r in records if r.get("event") == "step"]
    timed = [r for r in steps if not r.get("timing_warmup")]
    vals = [r for r in records if r.get("event") == "val"]
    hs = [r for r in records if r.get("event") == "hellaswag"]
    mfus = [r["mfu"] for r in timed if r.get("mfu") is not None]
    mems = [r["max_mem_gb"] for r in steps if "max_mem_gb" in r]
    return {
        "run_id": manifest.get("run_id", run_dir.name),
        "status": manifest.get("status"),
        "parallel": manifest.get("parallel"),
        "world": manifest.get("world"),
        "device": manifest.get("device"),
        "steps": (steps[-1]["step"] + 1) if steps else 0,
        "tokens_seen": steps[-1]["tokens_seen"] if steps else 0,
        "tokens_per_s": statistics.median(r["tokens_per_s"] for r in timed) if timed else None,
        "mfu": statistics.median(mfus) if mfus else None,
        "n_timed_steps": len(timed),
        "max_mem_gb": max(mems) if mems else None,
        "final_val_loss": vals[-1]["val_loss"] if vals else None,
        "hellaswag_acc_norm": hs[-1]["acc_norm"] if hs else None,
        "hellaswag_n": hs[-1]["n"] if hs else None,
        "git_sha": manifest.get("git_sha"),
        "peak_source": manifest.get("peak_source"),
    }


def _fmt(value: Any, spec: str) -> str:
    if value is None:
        return "—"
    return format(value, spec)


def runs_table(rows: list[dict[str, Any]]) -> str:
    head = (
        "| run | status | parallel | GPUs | device | steps | tokens | tokens/s (median) | MFU | "
        "peak mem (GiB) | val loss | HellaSwag acc_norm |\n|" + "---|" * 12 + "\n"
    )
    body = ""
    for r in rows:
        n_hs = "" if r["hellaswag_n"] is None else f" (n={r['hellaswag_n']})"
        body += (
            f"| `{r['run_id']}` | {r['status']} | {r['parallel']} | {r['world']} | {r['device']} | "
            f"{r['steps']} | {r['tokens_seen']:,} | {_fmt(r['tokens_per_s'], ',.0f')} | "
            f"{_fmt(r['mfu'], '.1%')} | {_fmt(r['max_mem_gb'], '.1f')} | "
            f"{_fmt(r['final_val_loss'], '.4f')} | {_fmt(r['hellaswag_acc_norm'], '.4f')}{n_hs} |\n"
        )
    return head + body


def bench_table(bench: dict[str, Any]) -> str:
    head = (
        f"Device: {bench['device']} · torch {bench['torch']} · triton {bench['triton']}\n\n"
        "| M × N | dtype | eager fwd / fwd+bwd (ms) | compile fwd / fwd+bwd (ms) | "
        "Triton fwd / fwd+bwd (ms) | Triton fwd+bwd GB/s | speed-up vs eager (fwd+bwd) | "
        "speed-up vs compile (fwd+bwd) | max abs err (dx) |\n|" + "---|" * 9 + "\n"
    )
    body = ""
    for r in bench["rows"]:
        cells = [
            f"{r['M']} × {r['N']}", r["dtype"],
            *(
                f"{r[k]['fwd_ms']:.3f} / {r[k]['fwd_bwd_ms']:.3f}"
                for k in ("eager", "compile", "triton")
            ),
            f"{r['triton']['fwd_bwd_gbps']:,.0f}",
            f"{r['speedup_fwd_bwd_vs_eager']:.2f}×", f"{r['speedup_fwd_bwd_vs_compile']:.2f}×",
            f"{r['max_abs_err']['dx']:.2e}",
        ]  # fmt: skip
        body += "| " + " | ".join(cells) + " |\n"
    return head + body


def write_results(
    runs: str | Path, out: str | Path, bench_dir: str | Path = "bench"
) -> dict[str, Any]:
    runs_dir = Path(runs)
    rows = [
        s
        for d in sorted(p for p in runs_dir.iterdir() if p.is_dir())
        if (s := summarize_run(d)) is not None
    ] if runs_dir.is_dir() else []  # fmt: skip
    parts = [
        "# Results\n\n_Generated by `gptfsdp report` from `runs/*/manifest.json`, "
        "`runs/*/log.jsonl` and `bench/*.json`; do not edit by hand._\n\n## Pretraining runs\n\n"
    ]
    parts.append(runs_table(rows) if rows else "_No runs yet._\n")
    if rows:
        sources = sorted({r["peak_source"] for r in rows if r["peak_source"]})
        parts.append("\nMFU peaks: " + "; ".join(sources) + ".\n" if sources else "")
    benches = sorted(Path(bench_dir).glob("*.json")) if Path(bench_dir).is_dir() else []
    parts.append("\n## Triton LayerNorm benchmark\n\n")
    parts.append(
        "".join(bench_table(json.loads(p.read_text())) + "\n" for p in benches)
        if benches
        else "_Not run yet._\n"
    )
    path = Path(out)
    path.write_text("".join(parts))
    return {"out": str(path), "n_runs": len(rows), "n_benchmarks": len(benches)}
